include:
  - board: seeeduino_xiao_ble
    shield: kb_1
    snippet: "input-trackball input-listener"
    artifact-name: kb_1_all_keys_test_restored
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
