manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-driver-paw3222
      url: https://github.com/beryu/zmk-driver-paw3222-kb-1
      revision: b885d0290f55b3c6432426508f439799b8ac6565
  self:
    path: config
