manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-driver-paw3222
      url: https://github.com/beryu/zmk-driver-paw3222-kb-1
      revision: f69222cc564e50d482e40e4e776f719c2a6a1448
  self:
    path: config
