manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-driver-paw3222
      url: https://github.com/beryu/zmk-driver-paw3222-kb-1
      revision: 4bb9ac89f0da0d7f8b37de4ea13c8c274624621c
  self:
    path: config
